name: Gradle Package

on: [push]

env:
  IMAGE_NAME: edu-platform

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: bootBuildImage --no-daemon --imageName=${{ env.IMAGE_NAME }}
        
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag & publish to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}
        VERSION=latest
        docker tag ${IMAGE_NAME} ${IMAGE_ID}:${VERSION}
        docker push ${IMAGE_ID}:${VERSION}
