name: Gradle Package

on:
  workflow_dispatch:
  release:
    types: ["published"]

env:
  IMAGE_NAME: edu-platform

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.6.1
        arguments: bootBuildImage --no-daemon --imageName=${{ env.IMAGE_NAME }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./build/libs/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Login to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: downcase REPO
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Tag & publish to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/${{ env.REPO }}/${IMAGE_NAME}
        VERSION=${{ github.sha }}
        docker tag ${IMAGE_NAME} ${IMAGE_ID}:${VERSION}
        docker push ${IMAGE_ID}:${VERSION}
